### ISSUE TITLE
More prominent search

### ISSUE THREAD

**Issue by chenglou** [reasonml/reasonml.github.io#1]
And maybe it let it float somewhere? It's nice to be able to stay on the page while searching

**Comment by Haroenv** [comment]
How is the search organised now? I notice that it isn't typo-tolerant, did you consider [docsearch](https://community.algolia.com/docsearch/)?

**Comment by chenglou** [comment]
We used to use docsearch actually. But this one is just querying graphQL. Since we were gonna reuse this doc template for BuckleScript, ReasonReact and more, it seemed easier to roll our own rather than request docsearch for each

**Comment by Haroenv** [comment]
We definitely have no issue in having many docsearch instances though, we love all those projects. Let me know if I can help more

**Comment by chenglou** [comment]
Ah! Thanks for the offer. Will keep this in mind then

**Comment by jaredly** [comment]
(given that it was easy to do, I'd rather avoid relying on an external service. adding typo-tolerance shouldn't be that hard either)

**Comment by chenglou** [comment]
Done
