### ISSUE TITLE
Translation infra

### ISSUE THREAD

**Issue by chenglou** [reasonml/reasonml.github.io#100]
Not sure what we should do here. High pri, as many translations are coming in.

**Comment by wincent** [comment]
Probably worth checking out Crowdin (https://crowdin.com/). Could ask the Yarn/Jest folks what their experience with it has been like.

**Comment by slonoed** [comment]
It's not a question of texts itself, but question of files. There should be an official way to add new translation. 

In [my PR](https://github.com/reasonml/reasonml.github.io/pull/111) I've just added subfolder.

And [this PR](https://github.com/reasonml/reasonml.github.io/pull/94/files) seems to have a lot of files changed.

**Comment by chenglou** [comment]
Done
