### ISSUE TITLE
reasonml windows installation instruction

### ISSUE THREAD

**Issue by OlegLustenko** [reasonml/reasonml.github.io#109]
Hi, as one of OS - windows user, I've been tried the different solution for installing reason on windows.
As last and most successful way which works mostly *out of the box*
is that package [ocaml-on-windows](https://github.com/fhelwanger/ocaml-on-windows).
Full IDE(vscode) support including merlin, refmt and other tools: 
![4abarrz3q-u79vtsntb3eq](https://user-images.githubusercontent.com/11524061/29711524-e9bbcd22-899d-11e7-83fb-3c1834d11802.png)

What do you think, should we add that package to documentation? I think it will help a lot of window-users newcomers.
I can make a PR

**Comment by kennetpostigo** [comment]
This sounds like really good news!

**Comment by chenglou** [comment]
Thanks! I'm merging this into #195
