### ISSUE TITLE
Font size too large [discussion]

### ISSUE THREAD

**Issue by rostero1** [reasonml/reasonml.github.io#11]
Looking at a [few](https://reasonml.github.io/guide/language/data-types) [pages](https://reasonml.github.io/guide/language/jsx), I find the font size to be too large.  It gets computed as '18px'.  I took a look at the documentation for other sites and find the text to be more readable, where they have a computed font size of '16px'.

See [Rust](https://doc.rust-lang.org/collections/borrow/trait.Borrow.html) and [Elixir](https://hexdocs.pm/elixir/Kernel.html)

**Comment by jaredly** [comment]
the other difference w/ those sites is that the body text uses a serif font -- I'd like to try that first before making the font size smaller, but I'm also open to bringing it down to 16px

**Comment by jaredly** [comment]
Ok, I changed the typography so there's a serif font for body text -- does it still feel too big? I tend to be a fan of larger fonts

**Comment by rostero1** [comment]
I'm actually surprised by how much an improvement that made.  I still prefer 16px or 17px over 18px, but it doesn't really bother me in the way it did before.

Thanks for the change.

**Comment by jsdf** [comment]
Just noticed that this made the big text home page all serif'd, was that intentional?

**Comment by chenglou** [comment]
Yeah that's Kida uncomfortable

**Comment by rickyvetter** [comment]
I like serif for the body text, but it does feel off on the main subtitle and on buttons.

**Comment by jaredly** [comment]
hah, definitely not intentional. gotta fix those

**Comment by chenglou** [comment]
Done
