### ISSUE TITLE
Playground eval timeout to avoid the infiniteness of infinite loops

### ISSUE THREAD

**Issue by glennsl** [reasonml/reasonml.github.io#131]
Auto-evaluating an accidental infinite loop caused by some intermediate editing state kind of sucks. Not just because the whole tab freezes, but you'll also lose everything you did up to that point. Even with the new localStorage, a kill & refresh will just land you straight back into the same infinite loop of suckiness.

So yea.. Timeout good.

**Comment by jaredly** [comment]
hmmm I wonder if we should just go to evaluation in a webworker. I have it in an iframe currently to keep open the possibility of having ReasonReact demos...
