### ISSUE TITLE
Outdated examples

### ISSUE THREAD

**Issue by glennsl** [reasonml/reasonml.github.io#148]
None of the examples on the front page have been updated for several months. They're all a bit out of date and some of them are quite frankly pretty non-idiomatic and lead people astray. One of them incorrectly defines a binding that already ships with BuckleScript, and that might introduce subtle bugs.

So the question is: How do we keep these up to date? Should we actively curate them, and fork them if necessary? Should we request more examples from the community and just swap them out over time? Or just warn about possible outdatedness and non-idiomaticness?

**Comment by chenglou** [comment]
> Or just warn about possible outdatedness and non-idiomaticness

That's convenient but sucks for users, let's optimize for users and not implementors, in general.

I think we should move these into reasonml-community so that at least you folks have write rights.

**Comment by chenglou** [comment]
Btw, I use `https://fabioz.github.io/mu-repo/` to mass manage repos under reasonml-community. Been useful a few times.
