### ISSUE TITLE
icon overlaps quickstart link on mobile

### ISSUE THREAD

**Issue by jaredly** [reasonml/reasonml.github.io#16]
maybe just hide the icon at mobile sizes?

**Comment by aweary** [comment]
@jaredly I don't think we should hide the logo, it's important for a consistent brand identity across the docs. Could we do a collapsible menu with a hamburger icon instead? That way we can have more menu items, whereas hiding the icon still limits us based on screen width.

**Comment by chenglou** [comment]
How do you get to the index page without the logo?

**Comment by chenglou** [comment]
Yeah hamburger icon please

**Comment by chenglou** [comment]
I've decide to go with two rows. No burger, no horizontal scrolling nav. Just this:

![localhost-8000- iphone 6](https://user-images.githubusercontent.com/1909539/30834167-c610a77c-a206-11e7-99be-dcb7dd946e43.png)
