### ISSUE TITLE
Named functions

### ISSUE THREAD

**Issue by tobia** [reasonml/reasonml.github.io#176]
File `src/pages/guide/javascript/syntax-cheatsheet.md` contains the following:

```
JavaScript                            |   Reason
--------------------------------------|--------------------------------
`function named(arg) {...}`           |  `fun named arg => ...`
`const f = function named(arg) {...}` |  `let f = fun named arg => ...`
```

This is wrong, because `fun named arg => ...` defines a curried function of two arguments, `named` and `arg`.

I did not prepare a PR because I'm not sure how to fix it. The first of the two could be written like this:

    let named = fun arg => ...

but the second one is beyond me. What does it mean in Javascript to assign a named function to a different name? What is the equivalent Reason code, if any?

**Comment by OvermindDL1** [comment]
> What does it mean in Javascript to assign a named function to a different name? What is the equivalent Reason code, if any?

There is none, it should probably be stated as such.  Functions don't have names in OCaml (they can be bound to a name, but the function itself does not have a name like javascript functions do).

**Comment by chenglou** [comment]
Thanks! There's indeed no equivalent. I've fixed it in the docs.
