### ISSUE TITLE
`ReasonReact` getting started link is not working properly

### ISSUE THREAD

**Issue by tejasbubane** [reasonml/reasonml.github.io#185]
Steps to reproduce:

1. Click on `ReasonReact` on the [QuickStart page](https://reasonml.github.io/guide/javascript/quickstart/).

2. It does not open anything, but changes the URL. I see these errors in the JS console:
![screen shot 2017-10-02 at 12 48 47 pm](https://user-images.githubusercontent.com/980783/31067387-3fdc1406-a770-11e7-801f-9c7cd0cdbed0.png)

3. Click on it again - reloads and opens the correct page.

Is this because the [/reason-react](https://github.com/reasonml/reason-react/tree/master/website) is a separate app?

**Comment by chenglou** [comment]
Great, this one again. Thanks for catching it! Fixed.
