### ISSUE TITLE
ctrl click or middle click on a link does not open in a new tab

### ISSUE THREAD

**Issue by kyldvs** [reasonml/reasonml.github.io#203]
Pretty much the title. Either of these ways of clicking should always open the link in a new tab.

**Comment by OvermindDL1** [comment]
They work for me (I tried the links at the top menubar), which links specifically are not working?

**Comment by kyldvs** [comment]
Ctrl clicking "Try" from https://reasonml.github.io/ opens up the "Try" page in the same tab. Pretty much all other internal links have same behavior.

Windows 10
Firefox Quantum browser

**Comment by OvermindDL1** [comment]
Ah, I found if I disabled my extensions then it breaks, I apparently have an extension that 'fixes' it (I really *really* hate it when websites break standard functionality, normal click should be same tab, ctrl/middle+click should be new tab).

**Comment by chenglou** [comment]
Our revamp will fix this. Give us ~2 weeks

**Comment by chenglou** [comment]
Done a while ago
