### ISSUE TITLE
Function with optional labeled arguments can't be built

### ISSUE THREAD

**Issue by MondoGao** [reasonml/reasonml.github.io#207]
I have tried to build a piece of code in [this chapter](https://reasonml.github.io/guide/language/function#optional-labeled-arguments)

```reason
/* radius can be omitted */
let drawCircle ::color ::radius=? () => {
  Js.log color;
  switch radius {
  | None => Js.log 1;
  | Some r_ => Js.log r_;
  }
};

let color = 1;
let curriedFun = drawCircle ::color;
```

and I got a error from ninja
```bash
   9 │
  10 │ let color = 1;
  11 │ let curriedFun = drawCircle ::color;

  This expression's type contains type variables that can't be generalized:
  radius::'_a? => unit => unit
```

I just started to learn reason, and I don't know why I got this, is it a bug or something?

**Comment by chenglou** [comment]
Aha, good point.

This is caused by the fact that at the end of the compilation `Js.log` takes whatever

**Comment by MondoGao** [comment]
Thx!
