### ISSUE TITLE
Playground compiler errors are broken after reason 3 upgrade

### ISSUE THREAD

**Issue by glennsl** [reasonml/reasonml.github.io#223]
(Some) compiler errors aren't properly captured after the upgrade to reason 3. It's not clear to me exactly which errors work as expected, and which do not, but here's an example of a snippet that does not work as expected:

    let f = (x) => .x + x;

Instead of a nice syntax error message, this gets printed to the console:

> Objects are not valid as a React child (found: object with keys {message, location}).

The same issue occurs with syntax errors in the OCaml pane. I think I've also come across syntax errors that *do* work, but I'm unable to find an example of it right now.

**Comment by chenglou** [comment]
Thanks. I've exposed a public API from the new release: https://github.com/facebook/reason#javascript-api
Reason-tools was using its own. When I display the error, it's now an object. And React doesn't like passing an object to a DOM child.
