### ISSUE TITLE
Use reasonreact template

### ISSUE THREAD

**Issue by chenglou** [reasonml/reasonml.github.io#224]
cc @rickyvetter @charlesmangwa

This way people will have a _much_ easier time translating the docs

**Comment by chenglou** [comment]
Done!

**Comment by CharlesMangwa** [comment]
Purfect! Time's up to add some translations

**Comment by chenglou** [comment]
=D it's here: https://crowdin.com/project/reason/fr#

Note that you can skip everything under `src/`. It's there for legacy reasons

**Comment by CharlesMangwa** [comment]
Gotcha!
