### ISSUE TITLE
Causing syntax error in /try with long file causes page to jump

### ISSUE THREAD

**Issue by kyldvs** [reasonml/reasonml.github.io#226]
When coding if you are working on a somewhat long piece of code in reasonml.github.io/try/ and then cause a syntax error the Ocaml section will get a large height and force the window you are coding in to be small. Watch this video for an example: https://www.youtube.com/watch?v=pc-1fhpjNk0

This makes it very painful to do quick prototyping of anything more than about a page. When writing code there are obviously going to be intermediate steps that are syntax errors.

**Comment by chenglou** [comment]
Should be fixed now
