### ISSUE TITLE
[try reason] Syntax errors are hard to debug because the line number is not give in the error

### ISSUE THREAD

**Issue by kyldvs** [reasonml/reasonml.github.io#227]
For example here it is not obvious the syntax error occurs on the line with `bax`. This can make it really hard to find the error in larger examples.

![screenshot-2017-10-31 try reason](https://user-images.githubusercontent.com/1830497/32257300-846f63ee-be71-11e7-8a97-07dfc2d11761.png)

**Comment by chenglou** [comment]
I yak shaved into making the linter integration with CodeMirror work. Except our doc currently inherits some rather unfriendly global styling. Once we clean up the architecture I'll display the error inline correctly. In the meantime, I've fixed displaying the error location in the message itself. Thanks!
