### ISSUE TITLE
Feature Request: Ability to auto-format examples in Try Reason

### ISSUE THREAD

**Issue by kyldvs** [reasonml/reasonml.github.io#228]
It would be nice to have the ability to let refmt format the code I write in try reason, via some button, hotkey, or after an X second delay

**Comment by rauschma** [comment]
Would love to have this feature! Useful when writing about ReasonML.

**Comment by chenglou** [comment]
Done!

**Comment by kyldvs** [comment]
Awesome, love the feature :) it works great!
