### ISSUE TITLE
Usage of the word "punning"

### ISSUE THREAD

**Issue by jayphelps** [reasonml/reasonml.github.io#235]
I think it's mostly apparent what the Reason docs mean by "punning", but I'm going to guess it's _very_ unlikely most people reading the docs would have heard the term. I hadn't, so I google'd and very few references of it can be found and they're not easy to find if you don't include keywords like "field" or "record".

Curious if my perception is wrong? Admittedly, I've never worked with OCaml people so I wouldn't be as familiar with related parlance.

**Comment by chenglou** [comment]
Punning is a term we share with JS. Not sure what term we should use instead. I think we should state this upfront in this case.

**Comment by jayphelps** [comment]
@chenglou have a handy example where punning is used in the JS community?

**Comment by chenglou** [comment]
I indeed can't find any example right now. But it's a term that's valuable to learn. We should document it more clearly then

**Comment by jayphelps** [comment]
That sounds good to me too. I agree it's a very valuable term I wish was more known.

**Comment by chenglou** [comment]
Thanks! Will go out in the next doc release

**Comment by barttenbrinke** [comment]
5 years and this is still the only good example that explains Javascript punning :) 👍
