### ISSUE TITLE
https://reasonml.github.io/try New Syntax not compiling in repl. FYI

### ISSUE THREAD

**Issue by idkjs** [reasonml/reasonml.github.io#236]
![screen shot 2017-11-08 at 09 30 50](https://user-images.githubusercontent.com/2370391/32538962-38026fa4-c468-11e7-9e8c-4c7d4550832f.png)

Just an FYI in case you havent noticed
[https://reasonml.github.io/try/?reason=DYUwLgBAxghsUFdgzCA6gSwHZZAJwgAoBnARwRjxGIC4JK8YBPIgewAcwNWsJiw82AOYBKERAC8APggBvAFAQIoSMGzVJEANqKlRAAwAaCAEZjAJhGHdSwgGZjAFmMBWKzaIA2YwHZjADnc9A2MHCE8gvUIzCGcIH0jbc1cAxJDY1OtgwmSM8JFdAF0Abl0AGQx+ADoAM1ZgABMAfVAasA9CDyUahF4YKChldUkZBWDglSIYYwAjYyhxCSHcUvG9YgB3DDAoAAsiMgoqYirCGCs+ckpqU5mLw+uTwgXxMbW9AB8iAGVWAFsQPRjL8ARA5hAQYCFhANrsQH1JBIljMIAAyVH0RFLQbSCH-QEwLrjL5NEb0AZEpQAXyJNOCBSUAEgAHI8EAeNS4YjyKnFIA](url)

**Comment by relekang** [comment]
That code snippet seems to be a mix of old an new syntax. This should be the same code in new syntax I think: https://reasonml.github.io/try/?reason=DYUwLgBAxghsUFdgzCA6gSwHZZAJwgF4IAKAZwEcEY8QyAuCGvGATxIHsAHMDDrcmDzYA5gEoJRAHwQA3gCgIEUJGDY6RCAG1FS0gAYANBACMxgExjDupSQDMxgCzGArFZukAbMYDsxgBzuegbGDhCeQXokZhDOED6RtuauAYkhsanWwSTJGeFiugC6ANy6ADIYZGAAdABmHMAAJgD6oLVgJB4kMFBQxmq4YtJyHkoqpDDGAEbGUEPEAyClwUpkAO4YYFAAFqSU1LRkWjCFxvs0dFpTpxDnh1pQhUMKKxAAPqQAyhwAtiDdVgg3z+JCmgOB-zmQzW2xAWCYREIxCmEAAZKiEUjiFBhhCAaN3hBmsMelACQBfDzkrJ6ABy-BANLG6jIugK5NKQA

**Comment by idkjs** [comment]
interesting because it was working as i remember it. Thanks!
