### ISSUE TITLE
Suggestion: remove jab at JavaScript’s `this`

### ISSUE THREAD

**Issue by rauschma** [reasonml/reasonml.github.io#244]
Quoting the docs: https://github.com/reasonml/reasonml.github.io/blob/source/src/pages/guide/language/object.md

> Just like a JavaScript object's `this`, our `this` has very erratic behavior depending on the context. Just kidding. Our `this` always points to the object itself correctly. Gotta learn from history.

I suggest removing the quoted sentences. I know I’m nitpicking, but hear me out:

* It’s not entirely true: the behavior is not “very erratic”. It could certainly be simpler, but it’s not that hard to make sense of it.
* Too many people already think it’s impossible to understand `this` in JavaScript. I’d prefer it if that notion were not perpetuated.
* This isn’t useful, actionable information.

Thanks for your work on ReasonML! I’ve been meaning to try out OCaml for years, now I finally get the chance.

**Comment by jordwalke** [comment]
I agree, and thank you for the feedback.

I do believe there’s some truth to what the original author was describing here. It took me a very long to understand JavaScript’s `this` in all the edge cases and I still somethings get it wrong. However I think the tone here isn’t conveying that point in a clear and helpful manner - we should improve the specificity and let the reader draw their own conclusion.

Thanks for bringing this to our attention. I believe official docs are a collaborative creation and should be mostly neutral in tone. Separately, I believe that personal blog posts bearing a single author’s name are a great place to exercise personal voice, biting commentary, and sometimes even controversial claims - the more the content is affiliated with a single indivudual, the more that person’s Voice should be present.

Does this sound good?

**Comment by rauschma** [comment]
Agree 100%.

My opinion on `this`: I use the following rules to keep things (moderately) straight.

* Many people see `function () {}` as normal and arrow functions as having a bound `this`. Instead, I prefer to see it as `function () {}` having the implicit parameter `this`. That implicit parameter shadows `this` in surrounding scopes. A better term for `function () {}` would be “method”. Arrow functions are the real functions.
* It looks like JavaScript has a single dot operator, but it actually has two – one for properties and one for methods:
    ```js
    obj.method('a', 'b') === obj.method.call(obj, 'a', 'b')
    ```
* I only use `this` inside ES6 method definitions (incl. arrow functions inside them) and never inside `function () {}`. There is even [an ESLint rule](https://eslint.org/docs/rules/no-invalid-this) for enforcing that.

**Comment by chenglou** [comment]
I'll fix this one, thanks. Though in general I do think a bit of joking around is fine in these docs. It's already boring enough reading through so many pages, that sprinkling around some jokes here and there is likely appreciated (at least according to feedback). We need to answer so many questions in Discord that are basically from people not wanting to read docs and in search of real-time alternatives. Formality and light-hearted-ness don't have to be mutually exclusive!

**Comment by rauschma** [comment]
@chenglou: I agree completely that keeping the tone light is a good thing!
