### ISSUE TITLE
Fix Quickstart page to mention inline JavaScript generation

### ISSUE THREAD

**Issue by davidgomes** [reasonml/reasonml.github.io#245]
It seems that JavaScript is now generated inline as opposed to being generated into the `lib/js` directory.

The docs have not yet been updated to reflect this change.

https://reasonml.github.io/guide/javascript/quickstart

**Comment by jaredly** [comment]
as I understand it the `in-source` flag is off by default (see [the schema](https://bucklescript.github.io/bucklescript/docson/#build-schema.json))

**Comment by chenglou** [comment]
Ah, the template has it on
