### ISSUE TITLE
Ligatures in <pre> blocks

### ISSUE THREAD

**Issue by dangodev** [reasonml/reasonml.github.io#249]
The `body` has `font-feature-settings: "kern", "liga", "clig", "calt";` set, which cascades down to `<pre>` blocks. This results in a weird `fi` ligature in the current font:

![screen shot 2017-12-05 at 11 09 15 am](https://user-images.githubusercontent.com/1369770/33617157-fe74d18c-d9ac-11e7-9837-9b236fedb475.png)

It actually copies just fine, but especially in code blocks it breaks the spacing, and becomes awkward to read. I’d suggest setting

```
pre {
  font-feature-settings: "normal";
}
```

Somewhere in the styles to fix this.

**Comment by chenglou** [comment]
Done!
