### ISSUE TITLE
When to use parens with `switch` argument is unclear

### ISSUE THREAD

**Issue by donut** [reasonml/reasonml.github.io#251]
In the [Comparisons to OCaml](https://reasonml.github.io/guide/ocaml) and [Pattern Matching!](https://reasonml.github.io/guide/language/pattern-matching) guides, it's not made clear when parentheses are necessary and when they aren't. I spent too much time debugging an "<UNKNOWN SYNTAX ERROR>" because I couldn't find anything wrong with my code.

From what I understand, they are not necessary when the argument is a single variable, but necessary in every other case.

**Comment by chenglou** [comment]
Thanks for the feedback. We're gonna enforce it to always have parens in the next version.
