### ISSUE TITLE
"ReasonReact" link doesn't work

### ISSUE THREAD

**Issue by gaearon** [reasonml/reasonml.github.io#253]
1. Go to https://reasonml.github.io/guide/what-and-why/
2. Search for "ReasonReact"
3. Click it

The URL bar changes but the website isn't displayed. (Apparently it doesn't realize the page is from another website.)

<img width="442" alt="screen shot 2017-12-08 at 1 29 15 pm" src="https://user-images.githubusercontent.com/810438/33767933-f4323e46-dc1b-11e7-813e-1af782e1f10e.png">

**Comment by claudiopro** [comment]
There's also another instance on https://reasonml.github.io/guide/javascript/quickstart/

**Comment by gaearon** [comment]
cc @chenglou this seems pretty important to fix?

**Comment by claudiopro** [comment]
Adding the protocol as proposed by @Roshanjossey is a functioning workaround. I'd suggest to apply this fix before a proper fix in Gatsby is found.

**Comment by chenglou** [comment]
Fixed
