### ISSUE TITLE
Quick start ideas

### ISSUE THREAD

**Issue by asolove** [reasonml/reasonml.github.io#26]
A few proposals for the quickstart section. I'm happy to do the work on these but wanted to get feedback first.

- [x] Fold the editor config section into the JS and native pages, since people may otherwise neglect to go back and do it.
- [x] Add some short hits to explain _what_ the quickstart steps are doing ("Bucklescript is a ...", "OPAM is the ...") so people know 
- [x] Gather some possible error cases and what to do about them.
- [x] Add a "Can't get it working?" section with where to get help. (Right now this is Discord, but that means that lots of people ask the same questions in there. It might be nice for the community to adopt a public, searchable, linkable place to provide definitive answers to common problems.)

**Comment by chenglou** [comment]
Sure!

Let's do 1 first. The editor setup is currently platform-specific anyway.

**Comment by chenglou** [comment]
Done
