### ISSUE TITLE
Javascript quickstart

### ISSUE THREAD

**Issue by zinoviev** [reasonml/reasonml.github.io#272]
Hi! I'm completely new to reasonml development and just want to share my first impression on onboarding. Info on main page quickstart told you just need

> npm install -g bs-platform
bsb -init my-first-app -theme basic-reason
Then, run it as usual:
cd my-first-app
npm run start

I would expect to see "hello world" in the terminal when following instructions like this,  but in fact, you need to open another terminal tab and run "node  src/demo.bs.js" When you know nothing about ocaml and bucklescript it's a little bit confusing and you need to figure out how to run your code.

**Comment by rainerlopez** [comment]
Yes, they are working to release something to solve it for us.
I "solved" it creating a starter package for my own using:
"devDependencies": {
    "bs-platform": "^2.1.0",
    "concurrently": "^3.5.1",
    "http-server": "^0.10.0",
    "sw-precache-webpack-plugin": "^0.11.4",
    "webpack": "^3.10.0"
  }

I'm about to upload it to github, but it's totally experimental.
I encourage you to take a look at ReasonReact: https://reasonml.github.io/reason-react/docs/en/installation.html

Cheers!
