### ISSUE TITLE
The "Type!" title in Language Basics is confusing

### ISSUE THREAD

**Issue by canadaduane** [reasonml/reasonml.github.io#273]
When I'm reading through the syntax of Reason, the "Type!" title may imply that the exclamation point is a syntax feature. I think the intent of the exclamation point is to show excitement? If so, I suggest either changing it to something like "Type System!" (which can't be easily confused with a word/punctuation reserved by the language) or removing the exclamation altogether.

**Comment by jordwalke** [comment]
Thanks for the suggestion. Want to PR?

**Comment by canadaduane** [comment]
Sure. What do you think of changing the other exclamation mark titles as
well? Eg `Variant!` and one other that I can't recall just now.

**Comment by iddan** [comment]
How about **bold**
