### ISSUE TITLE
Unicode strings break playground

### ISSUE THREAD

**Issue by bgoscinski** [reasonml/reasonml.github.io#280]
Repro: https://reasonml.github.io/try/?reason=DYUwLgBAtgngymAThAvBA3gKwM4B8CyMEAMgJZhigQCCwwpA5gIZgD2ygvBuBQO7jgL4BuAFBDQkWAmRoJSIbgB8EAFLYAdJNIA7BqsQgADsCYBjEAAoARLXrM2iCwBoIF2+wsBKOYpXqkWnXqGJuYWhI7OAJqsAK72ngrKahraugZGpmZYeK6cPPxOWbjRmqTG7JoQgHwbgCG7vNh88d5qwKwMQA

**Comment by codekiln** [comment]
[Updated link](https://reasonml.github.io/en/try.html?reason=DYUwLgBAtgngymAThAvBA3gKwM4B8CyMEAMgJZhigQCCwwpA5gIZgD2ygvBuBQO7jgL4BuAFBDQkWAmRoJSIbgB8EAFLYAdJNIA7BqsQgADsCYBjEAAoARLXrM2iCwBoIF2+wsBKOYpXqkWnXqGJuYWhI7OAJqsAK72ngrKahraugZGpmZYeK6cPPxOWbjRmqTG7JoQgHwbgCG7vNh88d5qwKwMQA): 

![image](https://user-images.githubusercontent.com/140930/36723564-a643b21c-1b7e-11e8-9c7d-562f3d25dceb.png)
![image](https://user-images.githubusercontent.com/140930/36723575-acf875ac-1b7e-11e8-9d05-b30bb6eea742.png)

**Comment by chenglou** [comment]
Little Alligator now works correctly
