### ISSUE TITLE
Javascript Syntax Cheatsheet: Boolean chart breaking

### ISSUE THREAD

**Issue by geoffdavis92** [reasonml/reasonml.github.io#288]
On the Javascript Syntax Cheatsheet page, the Boolean comparison chart is breaking into multiple extra cells where it should be only 2 cells. 

![JS syntax cheatsheet boolean chart break](https://image.prntscr.com/image/BMRix45CTKm4KuKYA8M5zA.png)

I forked the repo and found that this chart is breaking on the "Logical OR" operator; this is causing the problem because the operator (1) uses the same Unicode character as the Markdown chart delimiter (2).

![OR operator versus Markdown chart delimiter](https://image.prntscr.com/image/yNotREiGT4Gq0I8oMR223Q.png)

I played around with it for a minute, and it doesn't appear as though back-slash escaping either `|` character works to fix this problem. Using `&#9474;`/"BOX DRAWINGS LIGHT VERTICAL" could be a solution for displaying two pipe-like characters and be similar in appearance (`││` versus `||`); this is not ideal if the intent is to allow visitors to copy/paste directly from this cheatsheet, as using the alternative vertical line would not be allowed in JS code.

Anyways, just wanted to bring this to your attention. I have [made this change](https://github.com/geoffdavis92/reasonml.github.io/blob/js-syntax-break/docs/syntax-cheatsheet.md#boolean) on my fork if swapping out Unicode characters is desired.

**Comment by yangshun** [comment]
I only saw this issue after making the #291. Apologies if there was duplicated effort. I checked the remaining sections and fixed the other occurrences using `<code>&#124;</code>`.

**Comment by geoffdavis92** [comment]
@yangshun looks good! Better solution than mine
