### ISSUE TITLE
Can't see errors when horizontal scrollbar is present in editor

### ISSUE THREAD

**Issue by kyldvs** [reasonml/reasonml.github.io#299]
In this state I have no way to scroll down:

![screenshot-2018-1-9 reason reason lets you write simple fast and quality type safe code while leveraging both the javasc](https://user-images.githubusercontent.com/1830497/34749127-9507ede2-f554-11e7-81a7-b56ef36715b7.png)

Windows 10
Firefox

**Comment by kyldvs** [comment]
Actually it does not seem to be the horizontal scrollbar, something is just wrong with the error.

[Link to code](https://reasonml.github.io/en/try.html?reason=LYewJgrgNgpgBAYQBYwMYGsAqBPADvAXjgG8AoOOWAFzgCMQQo4iAKAfQC46GoBKOLhAB2ASxoEAfHBa8A3BXKUYNEUPHTOcVVX6DR4qTNmkAvsdKhIsOAHUATgENczEoupawMNWOwuWADy4AcgddOBDmKX9zCnd6Rj9A7kYwgCkAZwA6eNgHIUjXCgpkNCw8GGyeALlFCgzMgCEeGDzMqhA2ACt0thyWoWrjCjNSN2UtNUSubTDtArIixBQMHHxM7UHauGjFEbGaADMhAEY-AD8QIRhghwKQgCYAGjgzu2UIOyFguzu7J7gjjdfmEWA9fvd+JJCkV3AB3Ry4fBgFwOOwAc1OULeVA+AyOLEuMBYqIxvDJQyK8KcSIpIwUsXGR2ObFhYiQbE8Bwc0Co6T8WwuVyBUIeBBEnm8VGwz1e70+33BYolVB8z0B4VuIrsILBWoh8y2cIRSJR6MxUmxuJY+MJxLNZJqiypiJgYFpxj27mADnQMEx0jOInSACUQLCADIgDCu6aTKE5SFSexOTJMlhB0MRqO+sA1L0+mD3c4ZsOR6NgWMGZJ8LjpuNSep9PKJ2wI1MnFiKQUwAjJ3DrZWqruWz69ts5R6KEtZ8ukPPjb2+gDMxZDpezMYmVYTtbmUMbzWbBT77eZrKo7M53KgvJY9JeI6EY5TE6na5nObnsiAA)

![screenshot-2018-1-9 reason reason lets you write simple fast and quality type safe code while leveraging both the javasc 1](https://user-images.githubusercontent.com/1830497/34749183-e1bc196a-f554-11e7-9cef-5e90df404fb2.png)

**Comment by chenglou** [comment]
I see the error: 

```
Line 22, 34: This expression has type bool -> Js.boolean but an expression was expected of type bool -> bool Type Js.boolean is not compatible with type bool
```

Can repro on ff

**Comment by chenglou** [comment]
Fixed
