### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by chenglou** [reasonml/reasonml.github.io#3]

**Comment by slonoed** [comment]
@chenglou I'd like to participate in translation process (Russian).
Do you already know how it should works? Same site with subroute, different site or something else?

**Comment by chenglou** [comment]
Not sure yet (cc @jaredly who might have ideas). Feel free to start the translation in parallel though!

**Comment by slonoed** [comment]
FYI: I just created folder `src/pages/ru` (ru — Russian) and everything works fine: links, navigation, etc.

**Comment by jaredly** [comment]
way cool!

**Comment by chenglou** [comment]
@slonoed mind submitting a PR? Still not sure how to architect this but it'd be good to get the translations in! =)

**Comment by slonoed** [comment]
I want to translate guide part at least.
Also I have problem to make a copy of index.js page. I need to figure out what wrong with it.

**Comment by hwclass** [comment]
Hi folks,

If it is possible, I would like to be in translating-into-Turkish process :)

Cheers

Baris

**Comment by chenglou** [comment]
Do it! =D

**Comment by kutyel** [comment]
I can translate to Spanish 🇪🇸  where can I start? 😄

**Comment by wojciech-bilicki** [comment]
Hey, guys! I'd like to translate docs to polish. I'll be able to start like in a month or so. Just wanted to let you know.

**Comment by taiju** [comment]
I'd like to try Japanese :jp: translation. Should I do it [here](https://crowdin.com/project/reason/ja)?

**Comment by chenglou** [comment]
cc @rickyvetter 

@taiju thanks! You can do it wherever for now. We're revamping the architecture to be more translation-friendly in a week or two. The actual translation can be copy pasted over afterward in the worst case

**Comment by chenglou** [comment]
Sorry I missed that link, yes, that's where you'd do the translation. Thanks!

**Comment by chenglou** [comment]
Now active!

**Comment by haskellcamargo** [comment]
Awesome! :brazil: translation is 66% in two days. I believe tomorrow we finish it all!
