### ISSUE TITLE
Google description issues

### ISSUE THREAD

**Issue by cmwall** [reasonml/reasonml.github.io#300]
<img width="663" alt="screen shot 2018-01-09 at 7 05 25 pm" src="https://user-images.githubusercontent.com/13528491/34751089-1e801bb0-f570-11e7-95e3-898cc82c0831.png">

The description for the site is bugging out for Google.

**Comment by chenglou** [comment]
cc @rickyvetter that's because of our redirect banner that's accidentally picked up

**Comment by mikaello** [comment]
This seems to have been fixed:

![google_reasonml](https://user-images.githubusercontent.com/2505178/50098963-48312c00-021d-11e9-8489-81df5438429c.png)

**Comment by chenglou** [comment]
Thanks
