### ISSUE TITLE
Weird syntax error in record type in playground

### ISSUE THREAD

**Issue by bgoscinski** [reasonml/reasonml.github.io#303]
1. I pasted reason code from https://bucklescript.github.io/docs/en/interop-cheatsheet.html#record-mode into playground (top-left corner) and got `Line 5:3-4 <UNKNOWN SYNTAX ERROR>`
2. I pasted ocaml version of the same code into ocaml input (bottom-left corner) and it got `refmt`ed into reason and compiled to JS (it crashed, but it's expected as `john` is not defined anywhere)
3. I focused reason version and changed it (added space after semicolon so it shouldn't have any semantic impact) and got error like in 1 (`Line 3:31-32 <UNKNOWN SYNTAX ERROR>` (line is diffrent because record type is formatted in different way))

![playground-bug](https://user-images.githubusercontent.com/5730169/34872170-4353a764-f790-11e7-88c8-20553ebd67cd.gif)

**Comment by chenglou** [comment]
Thanks. We're now warning against the `##` infix operator
