### ISSUE TITLE
Warn about `Str`

### ISSUE THREAD

**Issue by rauschma** [reasonml/reasonml.github.io#307]
This seems to be the most frequently asked question on Discord: “Why can’t I use module `Str`?”.

Possible solution: add a warning to the beginning of the following page. https://reasonml.github.io/api/Str.html

**Comment by bobzhang** [comment]
I will remove str from the distribution, is that good?

**Comment by OvermindDL1** [comment]
What is wrong with `Str`?  What other options do you have when using regex on native builds?

**Comment by rauschma** [comment]
That’s a good point: you want `Str` for native. A warning on top of `Str` would probably be best, but I don’t know how difficult that is to do.

**Comment by chenglou** [comment]
Done in bsb's error messages.
