### ISSUE TITLE
JSX desugaring docs

### ISSUE THREAD

**Issue by gilbert** [reasonml/reasonml.github.io#311]
In the [JSX docs page](https://github.com/reasonml/reasonml.github.io/blob/9b8a4932f35c30d574e82bb0a4a5084aabfb8c66/docs/jsx.md) there are two examples that seem to conflict:

```jsx
<MyComponent foo={bar} />
becomes...
([@JSX] MyComponent.make(~foo=bar, ~children=[], ()));

...and...

<MyComponent> foo bar </MyComponent>
becomes...
([@JSX] MyComponent.createElement(~children=[foo, bar], ()));
```

Does `<Comp>` desugar to `Comp.make` or `Comp.createElement` ?

**Comment by jaredly** [comment]
Yeah so there are actually two steps here -- the Reason parser turns it into `MyComponent.createElement`, and the jsx ppx turns that into `MyComponent.make`....

**Comment by gilbert** [comment]
Thanks for the reply. What's the purpose of the intermediary step? Does it allow libraries to hook in?

**Comment by chenglou** [comment]
Yep!
