### ISSUE TITLE
No example of List.map in quick start guide

### ISSUE THREAD

**Issue by hoffmeyer** [reasonml/reasonml.github.io#317]
I just finished reading the language basics off the main website, which was a pleasant read, but I was surprised by the lack of an example of mapping a function over a list, which I personally prefer over mutable loops, which are described in detail.

Are there any reason for leaving this out of the language basics?

Actually I couln't find any description of this in the official docs anywhere, only code examples from different repos.

**Comment by chenglou** [comment]
It's in the API section =) https://reasonml.github.io/api/List.html
