### ISSUE TITLE
In the Pattern Matching page, an example isn't explained

### ISSUE THREAD

**Issue by FrankelJb** [reasonml/reasonml.github.io#339]
Going through the Language Basics on Pattern Matching, in the Tips and Tricks section is an example that is suggested but not explained:
```
let optionBoolToJsBoolean = (opt) =>
  switch (opt) {
  | Some(true) => Js.true_
  | Some(false)
  | None => Js.false_
  };
```
It is not clear why the `| Some(false)` works. I couldn't find a reference to using patterns without `=>` statements.

**Comment by zploskey** [comment]
If it does not have `=>` it falls through to the next pattern that does. It would be good to briefly explain that.

**Comment by chenglou** [comment]
It's explained in the Usage section, "You can even have many patterns going to the same result"

Maybe that's not prominent enough?

**Comment by FrankelJb** [comment]
I didn't notice the explanation, I figured it out by trial and error. I wanted to bring this to your attention and will close the issue.
