### ISSUE TITLE
Code sample on landing page overflows on mobile

### ISSUE THREAD

**Issue by lorenzleutgeb** [reasonml/reasonml.github.io#341]
Hello!

I would like to make you aware of a layout glitch in the hottest area of your landing page.

The attached screenshot are Firefox 59.0.2 and Chrome 65 on top of Android 8.1.0

![screenshot_20180329-175524](https://user-images.githubusercontent.com/542154/38099317-980f327a-337a-11e8-9aa9-7896e77c7458.png)
![screenshot_20180329-175149](https://user-images.githubusercontent.com/542154/38099328-9db0b0dc-337a-11e8-936e-36011396ea95.png)

**Comment by chenglou** [comment]
Thanks
