### ISSUE TITLE
Syntax highlighting for Reason broken

### ISSUE THREAD

**Issue by henrebotha** [reasonml/reasonml.github.io#354]
On the Interop page, there's this Reason snippet where the comment is not correctly highlighted:

![image](https://user-images.githubusercontent.com/5593874/38729763-4f042b44-3f14-11e8-85c6-d8345f0e8f91.png)

Compare to how Github's UI renders interop.md:

![image](https://user-images.githubusercontent.com/5593874/38729786-5e6ebf68-3f14-11e8-85f0-095da358ee99.png)

highlight.js (the library being used by this project for syntax highlighting) doesn't currently support Reason syntax. However, Github's syntax highlighting detects it successfully. Could we use what they're using?

**Comment by chenglou** [comment]
Thanks, fixed.
