### ISSUE TITLE
Reason logo usage and/or modification permission

### ISSUE THREAD

**Issue by kepi74** [reasonml/reasonml.github.io#357]
Hello,

we are starting [Reason Prague](https://www.meetup.com/Reason-Prague/) meetup group and we would like to slightly modify Reason logo for purpose of our group. Unfortunately, we didn't find licence or usage rules of Reason logo on yours site. Can you write us if there are any restrictions how can be logo used and eventually who can grant us this permission.

Than you for any help you can provide

Pavel

**Comment by chenglou** [comment]
Fine to use it! Other meetup groups do the same.
