### ISSUE TITLE
Converting from JS

### ISSUE THREAD

**Issue by montogeek** [reasonml/reasonml.github.io#381]
Converting from JS guide should have more documentation regarding what you should install in your project, what you should add to your npm scripts, etc.

**Comment by kevinsimper** [comment]
@montogeek I wrote a tutorial here, does that cover what you were thinking about? https://medium.com/@kevinsimper/how-to-start-a-minimal-reasonml-project-without-boilerplate-57e9e19bfa88

**Comment by montogeek** [comment]
It should be in the official docs.

**Comment by kevinsimper** [comment]
@montogeek Thank you, I wrote it first outside, but I will try to add it to the official docs 👍
