### ISSUE TITLE
Code examples appear to not be monospaced font

### ISSUE THREAD

**Issue by jordwalke** [reasonml/reasonml.github.io#385]
From the comparison-to-ocaml page:

<img width="460" alt="screen shot 2018-05-27 at 10 15 50 pm" src="https://user-images.githubusercontent.com/977348/40598317-cffcddea-61fb-11e8-9edb-cb360cbe5171.png">

I think this is a regression, but I'm not sure what caused it.

**Comment by chenglou** [comment]
Fixed
