### ISSUE TITLE
Search right language in search bar

### ISSUE THREAD

**Issue by endiliey** [reasonml/reasonml.github.io#388]
It seems that reasonml website search bar doesn't search the correct language. It only search english documentation when I'm actually on Espanol

<img width="938" alt="wrong" src="https://user-images.githubusercontent.com/17883920/40927079-71e5d198-6850-11e8-9b58-da8aeed968a6.png">

I saw @chenglou restricting the doc search to 'english' only based on https://github.com/algolia/docsearch-configs/pull/292 because searching 'foo' gives 5+ result across all languages. Till today https://github.com/algolia/docsearch-configs/blob/master/configs/reason.json is still restricted to english

Some suggestion.
You can search the right language by reverting that commit and change this
https://github.com/reasonml/reasonml.github.io/blob/95f4d390b50f823a7b88f21098fec30bc34c6162/website/siteConfig.js#L265-L268

to
```js
  algolia: {
    apiKey: "966d1e412f67114a07dc0afe44b19b53",
    indexName: "reason",
    facetFilters: ["lang:LANGUAGE"]
  },
``` 

P.S : I can help to submit a PR if you want

This is because `LANGUAGE` will be replaced by Docusaurus to the right language. 
Source code:
https://github.com/facebook/Docusaurus/blob/d28b864a59fabeea45add8c090a13de7d0530de5/lib/core/Site.js#L128-L142
```js
algoliaOptions: ${JSON.stringify(
   this.props.config.algolia.algoliaOptions
)
 .replace('VERSION', docsVersion)
 .replace('LANGUAGE', this.props.language)}
```

Example on my site:
Only search for 'korean' documentation when on 'korean'
<img width="957" alt="dynamic language" src="https://user-images.githubusercontent.com/17883920/40927808-40d78aea-6852-11e8-964b-8000d03d9070.png">

Only search for 'chinese' documentation when on 'chinese'
<img width="960" alt="cn" src="https://user-images.githubusercontent.com/17883920/40927863-60993720-6852-11e8-9128-3241e01ccb48.png">

cc @joelmarcey @yangshun . Maybe we should update Docusaurus documentation on search bar. I don't think user know this extra processing that we did. We only refer them to https://community.algolia.com/docsearch/documentation/ 😢 based on https://docusaurus.io/docs/en/search.html#enabling-the-search-bar

**Comment by endiliey** [comment]
I personally think the extra search option should at least be put back, especially information of
```Any occurrences of "VERSION" or "LANGUAGE" will be replaced by the version or language of the current page, respectively``` is very useful. Because this extra processing is only done via Docusaurus through https://github.com/facebook/Docusaurus/blob/d28b864a59fabeea45add8c090a13de7d0530de5/lib/core/Site.js#L128-L142

**Comment by endiliey** [comment]
@JoelMarcey I think good first issue is better so that more ppl can contribute. Sometimes those first contributor even stays around

**Comment by chenglou** [comment]
@endiliey so this'll work today if you make the change right? Feel free to submit a PR to change it for reasonml here!
