### ISSUE TITLE
type nonrec not supported in playground

### ISSUE THREAD

**Issue by christophe-riolo** [reasonml/reasonml.github.io#391]
The following code is valid reasonml but does not work in the playground:

```reason
type nonrec t = int;
```

The problem is the keyword `nonrec` not being recognized.

**Comment by jaredly** [comment]
The new playground (which we'll be transitioning over to Soon™) supports in [demo](https://reason.surge.sh/?syntax=Reason&code=C4TwDgpgBAdg9jAThAxlYUC8UCWNgDcQA&canvas=200)

**Comment by christophe-riolo** [comment]
Oh well perfect 👌
