### ISSUE TITLE
Ru-lang error

### ISSUE THREAD

**Issue by userbq201** [reasonml/reasonml.github.io#401]
link - `https://reasonml.github.io/docs/ru/destructuring`
line - `Деструктурирование позволяет делать аннотации типоы.`

error in `типоы => типов`

**Comment by userbq201** [comment]
link - `https://reasonml.github.io/docs/ru/mutation`
line - `Значение из ref можно получить используя оператор !:`

error `^` instead `!`

**Comment by chenglou** [comment]
Hello! Thanks; fixed and will push soon. Btw, you can click on the translate icon on the upper right of the page and help translate our docs =).
