### ISSUE TITLE
In what-and-why.md, "Don't Like Reason?" section, mention Haxe as well.

### ISSUE THREAD

**Issue by uvtc** [reasonml/reasonml.github.io#412]
In the [what-and-why.md doc](https://reasonml.github.io/docs/en/what-and-why) "Don't Like Reason?" section, [Haxe](https://haxe.org/) should also be included in the alternatives list there, as it also has OCaml under the hood. Not sure what quip I'd use to describe it though.

**Comment by chenglou** [comment]
Thanks, added!
