### ISSUE TITLE
[Bug] Playground is crash with `(")`

### ISSUE THREAD

**Issue by DanSnow** [reasonml/reasonml.github.io#416]
## Error message

```plain
Uncaught TypeError: Cannot destructure property `startLine` of 'undefined' or 'null'.
```

## Reproduce

1. Go to Reasonml Playground
2. Type `(")`

Or use this url: https://reasonml.github.io/en/try?rrjsx=true&reason=BQIglEA

Seem it try to destructure `undefined` at
https://github.com/reasonml/reasonml.github.io/blob/source/website/playground/try.js#L332

**Comment by kevinsimper** [comment]
Yeah that is not a pretty bug, it is even difficult to fix because it remembers that last code you wrote!

**Comment by alexeyknyshev** [comment]
Faced same bug

**Comment by chenglou** [comment]
Sorry about that. This is fixed now
