### ISSUE TITLE
maybe a bug in doc, about opening module syntax

### ISSUE THREAD

**Issue by andares** [reasonml/reasonml.github.io#419]
you can see it in there:

https://reasonml.chat/t/open-module-syntax-error/920

**Comment by andares** [comment]
If it is work with switch block, I think it should show user block mode in case.

**Comment by kevinsimper** [comment]
@andares Which page is it on?

**Comment by andares** [comment]
this page:

https://reasonml.github.io/docs/zh-CN/module#open-ing-a-module


I think ```switch``` maybe is a block, but it is deceptive.

I follow the example in doc try to write:

```
Hashtbl.(
  myHastbl.add(...)
);
```

it will be fault.

I think can add more example (use block ```{}```) in this will be better.

**Comment by chenglou** [comment]
Thanks
