### ISSUE TITLE
Playground: error in generated JS

### ISSUE THREAD

**Issue by svoynow** [reasonml/reasonml.github.io#423]
[here](https://reasonml.github.io/en/try?rrjsx=true&reason=LYewJgrgNgpgBAFwJ4Ad4GULGAQwEaxwC8cA3gFByKrwIDclcsCcAXjAE4gBciDVzODjBheLIgD5ExKfXIBfBuVCRCmYMTKMV0eAFkcAa3gkAFAFFYwGADsEAZ17rcBGAEoZWqgJgsOMAGM4eyxNUxgrWwcPSS9vKnsAdwBLBACAC3DIu3sPCniqAB84AG0AXU9LGGscgDp2LkZ44pKADwAaOFru1vsK2Kqah1rhMFMO4Kxx3Lcm73k5haoFxXJlcF04AEk7dU11WoNjU3zqNGkSZLt+Jl82ThBNAAYbwVGwiaQYqVa4AGo4EgGPI3EoAFL2WpQEAAc1M9gQHCuMIA+iAAGYoq4IUw7BAHELAUwlACM7QATO0AMztAAsZTcjKUQA) 

Gives me:

`Uncaught Error: Cannot find module 'stdlib/curry'` 
at this line
`var Curry = require("stdlib/curry");`

I'm fairly sure this snippet worked fine a few days ago, so it seems like something changed.

**Comment by chenglou** [comment]
Fixed, thanks
