### ISSUE TITLE
Pipe operator is no longer documented

### ISSUE THREAD

**Issue by ghoullier** [reasonml/reasonml.github.io#435]
Seems pipe operator "|>" is no longer documented but still works.

```reason
let doubled = [1, 2, 3]
  |> List.map(a => a * 2);
```

Is this syntax always recommended?

**Comment by chenglou** [comment]
It's actually on this page: https://reasonml.github.io/api/Pervasives.html

But yes, we recommend [fast pipe](https://reasonml.github.io/docs/en/fast-pipe) instead

**Comment by yawaramin** [comment]
I recommend reopening this and documenting `|>` explicitly (if briefly) just so newcomers are aware when and when not to use it. Right now we can get into a situation where people are seeing `->` as the recommended pipe operator and thinking they can just swap out all examples of `|>` in the community, with `->`, and then running into the inevitable compile errors.

**Comment by baransu** [comment]
@yawaramin I totally agree with you. It's really hard to teach newcomers what the difference is and why we have two operators that are not interchangeable. We should provide documentation about both and the comparison with the explanation which one is preferred and why.

**Comment by matthewess** [comment]
I'm just learning Reason, specifically for native compilation, and I have to say that the docs had me pretty confused until someone in Discord explained. I would say this issue should be reopened, perhaps, and I would _also_ argue that maybe the Reason docs should be updated to mention that pipe first is only supported by Bucklescript.
