### ISSUE TITLE
Incomprehensible paragraph in 'Fast Pipe' section

### ISSUE THREAD

**Issue by markus-willems** [reasonml/reasonml.github.io#438]
This paragraph is rather incomprehensible.
> ## Pipe Into Variants
> There are good justifications on why a variant's contructors [sic] are not function calls. Though it's a bit inconvenient practically still. For example, it'd be nice to be able to Variant constructors not being functions are sometimes a bit inconvenient. We've piggy-backed on top of fast pipe to make this work:

Direct link: https://reasonml.github.io/docs/en/fast-pipe#pipe-into-variants

**Comment by chenglou** [comment]
Thanks!
