### ISSUE TITLE
Quickstart instructions are incomplete

### ISSUE THREAD

**Issue by p-mongo** [reasonml/reasonml.github.io#450]
The main page (https://reasonml.github.io/) shows the following quick start instructions:

<pre>
npm install -g bs-platform
bsb -init my-first-app -theme basic-reason
cd my-first-app
npm run start
</pre>

When I run `npm run start`, I get the following output:

<pre>
averagest% npm run start

> reason-cms@0.1.0 start /home/w/apps/reason-cms/reason-cms
> bsb -make-world -w

>>>> Start compiling
[3/3] Building src/Demo.mlast.d
[1/1] Building src/Demo-ReasonCms.cmj
>>>> Finish compiling
</pre>

If this started a web server, it doesn't say which port the server is listening on. I looked at netstat output and didn't see anything on ports 80* thus I am not clear on whether this in fact starts a server.

At the end of the instructions I do not have a working Reason app I can look at in a browser.

**Comment by p-mongo** [comment]
The react theme instructions (#451) also do not print a port number where one would find the web server, if they start a web server.

**Comment by mlms13** [comment]
It doesn't look like the script runs a web server, it only starts watching the Reason files and re-compiling them when they change. It also looks like the bsb theme doesn't include an HTML file or any JS bundling, so it's still several steps away from showing you something in the browser.

But that "Quick Start" section of the homepage now links [here](https://reasonml.github.io/reason-react/docs/en/installation), which gives a much more complete path to actually seeing something in the browser, so maybe that's good enough?

**Comment by p-mongo** [comment]
I would say any tutorial that ends with the app being rendered in a web browser would satisfy the requirements of a basic quick start.
