### ISSUE TITLE
Quickstart instructions reference both basic and react themes

### ISSUE THREAD

**Issue by p-mongo** [reasonml/reasonml.github.io#451]
The main page (https://reasonml.github.io/) gives the following quickstart instructions:

<pre>
npm install -g bs-platform
bsb -init my-first-app -theme basic-reason
cd my-first-app
npm run start
</pre>

Note it uses basic-reason theme.

Underneath those instructions there is a "read more" link leading to https://reasonml.github.io/reason-react/docs/en/installation, which offers the following *different* instructions for getting started using react theme:

<pre>
npm install -g bs-platform
bsb -init my-react-app -theme react
cd my-react-app && npm install && npm start
# in another tab
npm run webpack
</pre>

The quickstart should pick one of these and use them in both locations.

**Comment by kevinsimper** [comment]
Hi @p-mongo

The first example is for reasonml and the second example is from the other project called reason-react which is based on reason, but is more of a framework. Hope that clears up the projects, that is why they are different :) The color at the top is also blue where reasonml is red :)

**Comment by p-mongo** [comment]
Okay thank you.
