### ISSUE TITLE
Broken link in Integer and Floats

### ISSUE THREAD

**Issue by francocorreasosa** [reasonml/reasonml.github.io#457]
There is [this URL](https://www.lexifi.com/blog/unboxed-floats/) being referenced from https://reasonml.github.io/docs/en/integer-and-float#design-decisions which is giving a 404 error.

**Comment by mikaello** [comment]
This seems to have been fixed, the new link now points to: https://www.lexifi.com/blog/ocaml/unboxed-floats-ocaml/

**Comment by francocorreasosa** [comment]
Excellent 💯
