### ISSUE TITLE
refmt definition

### ISSUE THREAD

**Issue by ianchanning** [reasonml/reasonml.github.io#471]
As far as I can tell, nowhere in the documentation does it actually explain what `refmt` is. It's referred to in various places but never actually defined within the documentation itself. People can search for it else where but it seems like it should be defined within the documentation.

![2018-11-15 21_38_08-if-else reason](https://user-images.githubusercontent.com/233318/48581005-eda46780-e920-11e8-8fbe-56112e61ea9c.png)

**Comment by kevinsimper** [comment]
@ianchanning That is a valid point, I think that would make sense! 👍

**Comment by ianchanning** [comment]
`refmt` and also FFI seems to be two things that are often referred to within Reason (both the docs and library developers) assuming that everyone knows what they are. I think this is because the docs come directly from BuckleScript which assumes OCaml knowledge. Both of these are common in lower level languages like OCaml, Go, Rust etc. but not in JavaScript.

ReasonML makes a fantastic step of trying to being JavaScript developers closer to this community but these terms are almost never used in the JavaScript ecosystem. So I think it would be useful to have some 'OCaml guide for JavaScript' developers. I might try and write up something unless there's a defacto guide that already exists
