### ISSUE TITLE
Documentation bug? Annotating `add` not `bar`.

### ISSUE THREAD

**Issue by mnieber** [reasonml/reasonml.github.io#479]
Hi, at the end of https://reasonml.github.io/docs/en/function, it says

    `let add: bar` annotates an existing value bar from the implementation file

Should it be "let add: bar annotates an existing value *of type* bar from the implementation file"? Because we are not annotating `bar` here, right?

Sorry, I'm new to ReasonML, so I might be missing someting.

**Comment by kevinsimper** [comment]
Hi @mnieber, no because the value does already exist, but this is when you make a `.rei` file, you define it again :)
