### ISSUE TITLE
Please upload 3.3.4 to opam

### ISSUE THREAD

**Issue by dysinger** [reasonml/reasonml.github.io#482]
Bucklescript uses ReasonML 3.3.4 currently. It's not on Opam. Installing native ReasonML 3.3.7 Opam causes some problems in reason-react with bs-platform's refmt.exe (from 3.3.4). The scenario is running refmt in your editor (my case emacs with reasonml 3.3.7) and then later trying to build with `bsb` which uses an embedded refmt.exe 3.3.4. I've encountered syntax errors reported from 3.3.4 and the bsb build halts.
 
![2018-12-03-110635_900x571_scrot](https://user-images.githubusercontent.com/447/49396052-45dab800-f6dc-11e8-926a-aa12071874b4.png)
![2018-12-03-111502_908x160_scrot](https://user-images.githubusercontent.com/447/49396060-4b380280-f6dc-11e8-8b80-737a5d259628.png)

We should be able to match Opam & BS versions of ReasonML at all times.

pretty please? /cc @jordwalke

**Comment by kevinsimper** [comment]
@dysinger It seems like it should be solved, can you upload it yourself to opam under your user? Then it would be a solution for others having the same problem?

**Comment by dysinger** [comment]
sorry for the late response. I guess that's fine.

**Comment by davesnx** [comment]
Reason 3.9.0 is now in opam https://opam.ocaml.org/packages/reason
