### ISSUE TITLE
Playground extremely slow for anything past 10 lines of code

### ISSUE THREAD

**Issue by chenglou** [reasonml/reasonml.github.io#5]
We should debounce. Though the bucklescript playground is super fast... http://bucklescript.github.io/bucklescript/js-demo/

**Comment by johann-sonntagbauer** [comment]
Hongbo Zhang released https://github.com/BuckleScript/bucklescript-playground
Maybe we could join forces here and not implement our own solution.

**Comment by chenglou** [comment]
Hongbo and I do talk actively =)

Yes, that'd be a nice goal.

**Comment by chenglou** [comment]
Ok, added debounce so that it's not a total pain. We should still unify these though

**Comment by chenglou** [comment]
Fixed! We use most of the same parts =)
