### ISSUE TITLE
Modules _can_ be passed to regular functions

### ISSUE THREAD

**Issue by mlms13** [reasonml/reasonml.github.io#586]
Currently the [module functions section](https://reasonml.github.io/docs/en/module#module-functions-functors) of the module page says, "However, modules are at a different 'layer' of the language than other common concepts, so we can't pass them to _regular_ functions."

But this is valid Reason:

```reason
clamp((module IntOrd), ~min=3, ~max=8, 9); // 8
```

Where `clamp` is a "regular" function defined using the `let` keyword.

**Comment by kyldvs** [comment]
We need to add better documentation on Functors/First Class Modules, but for now in my update I remove the confusing line that you mention :)
