### ISSUE TITLE
Middle click swallowed

### ISSUE THREAD

**Issue by chenglou** [reasonml/reasonml.github.io#65]
On localhost this opens a new tab. On prod it turns into a left click.

cc @bassjacob

**Comment by johann-sonntagbauer** [comment]
the behaviour varies between browsers, but as a rule of thumb the links should be absolute to proper support that feature

**Comment by bassjacob** [comment]
Has this fix been deployed? I'm not seeing changed behaviour on the site.

**Comment by johann-sonntagbauer** [comment]
@bassjacob nope not deployed yet. To be honest, don't know exactly how the deployment is triggered. Is it a manual task?

**Comment by bassjacob** [comment]
no idea 😛 @chenglou probably does something

**Comment by chenglou** [comment]
Yeah: https://github.com/reasonml/reasonml.github.io#building

Published, thanks!

**Comment by rauschma** [comment]
Command-click (Windows: Ctrl-click) still doesn’t work for me (Mac).

**Comment by johann-sonntagbauer** [comment]
@rauschma nice catch. The problem can be fixed by simply updating gatsby-link dependency.
Will try to formulate a PR
