### ISSUE TITLE
JSX parser error

### ISSUE THREAD

**Issue by acierto** [reasonml/reasonml.github.io#79]
This line produces an error
`<span className="filter-label"><span>(ReasonReact.stringToElement "Has interface")</span></span>`
Though if to format it manually like this, then it works:
```
<span className="filter-label">
     <span>(ReasonReact.stringToElement "Has interface")</span>
</span>
```

![screen shot 2017-08-11 at 12 43 39](https://user-images.githubusercontent.com/2265094/29210218-be7f4df2-7e92-11e7-861b-3f12313e07d0.png)

So as you can see from error, it complains that code contains some reserved BuckleScript keyword.

P.S.
Was redirected from BuckleScript team: https://github.com/BuckleScript/bucklescript/issues/1874

**Comment by chenglou** [comment]
You might be hitting an edge case from the JSX because of the `><` part. This is a known problem. Keeping this issue open until we fix it

**Comment by chenglou** [comment]
Fixed
