### ISSUE TITLE
Some small "bugs"

### ISSUE THREAD

**Issue by xvw** [reasonml/reasonml.github.io#8]
Hi ! 
The new ReasonML's website is really cool, but I have point some little bugs : 

- [x] https://reasonml.github.io/guide/tools the pictures are dead
- [x] https://reasonml.github.io/guide/ocaml in the OCaml part, there are some anoying `\` in the code

**Comment by chenglou** [comment]
Thanks for the report! I've fixed the second one. @jaredly what do you think of the image issue? https://github.com/gatsbyjs/gatsby/issues/501

Would be nice not needing to drop down to JS files for that

**Comment by xvw** [comment]
👍 Top
