### ISSUE TITLE
Right-clicking on a relative link triggers navigation

### ISSUE THREAD

**Issue by folz** [reasonml/reasonml.github.io#84]
## Steps to reproduce

Right-click on a link on reasonml.github.io that points to somewhere else on reasonml.github.io.

## Expected behavior

I would be able to view the context menu for the link without navigation

## What actually happens

My browser navigates to the link I right-click on.

## Additional information

This doesn't appear to happen on other sites using Gatsby (e.g., Segment's blog, https://www.gatsbyjs.org/).

I'm using Firefox 56 on Linux.

**Comment by chenglou** [comment]
Done a while ago
