### ISSUE TITLE
Option to try new syntax in playground

### ISSUE THREAD

**Issue by dc-mak** [reasonml/reasonml.github.io#90]
I realise the [new proposed syntax #1299 ](https://github.com/facebook/reason/pull/1299) is a bit of a minefield, but would it be possible to have an option on the Try page to explicitly select the WIP (with appropriate warnings, 'beta' status, summary of differences/changes, code-snippets showing real-life examples/advantages, etc) branch.

I would like to try it for myself before jumping to conclusions and the only way right now seems to download the repo, switch branch and use rtop/refmt or build and run the website locally. This may also help with testing, as people try to (a) understand and explore and (b) think up pathological case and (c) convince people of benefits.

**Comment by chenglou** [comment]
Done
