### ISSUE TITLE
New playground fails to compile code that is incorrectly pretty-printed, when it would normally work fine

### ISSUE THREAD

**Issue by glennsl** [reasonml/reasonml.github.io#91]
OCaml's pprintast has some bugs (among other flaws). One of those bugs is that `#` operators will be printed incorrectly. E.g.

```ml
let f thing => thing##x
```

will be printed as
```ml
let f thing = ## thing x
```

And because the playground compiles the pretty-printed OCaml instead of using the AST from refmt directly, it will fail to compile. When refmt is used normally as part of the build process however, it uses the AST instead and will compile correctly.

**Comment by glennsl** [comment]
This specific issue will be fixed in 4.06 https://github.com/ocaml/ocaml/pull/1243

**Comment by chenglou** [comment]
I'm wondering if we can directly pass the refmt's parsed ast to bs on the web? cc @bobzhang

**Comment by bobzhang** [comment]
If you supply the reason parser to our side as we suggested before, yes
